# Generated by Django 5.2.7 on 2025-10-22 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlayerClub_Data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='red_cards',
            new_name='blocks',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='total_assists',
            new_name='challenges_attempted',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='total_goals',
            new_name='challenges_won',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='height_cm',
            new_name='clean_sheet_percentage',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='total_win',
            new_name='clearances',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='yellow_cards',
            new_name='passes_attempted',
        ),
        migrations.RemoveField(
            model_name='club',
            name='code',
        ),
        migrations.RemoveField(
            model_name='club',
            name='country',
        ),
        migrations.RemoveField(
            model_name='club',
            name='stadium',
        ),
        migrations.RemoveField(
            model_name='player',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='club',
            name='expected_xag',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='club',
            name='expected_xg',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='club',
            name='league',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='club',
            name='season',
            field=models.CharField(default='2425', max_length=20),
        ),
        migrations.AddField(
            model_name='club',
            name='total_assist',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='club',
            name='total_goal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='Progressive_Carries',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='Progressive_Passes',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='Progressive_Receptions',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='assists',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='born',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='clean_sheets',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='goals',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='nation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='npxg',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='pass_accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='passes_completed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='save_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='saves',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tackles',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='tackles_won',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='xag',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='xg',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='club',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='player',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='PlayerClub_Data.club'),
        ),
        migrations.AlterField(
            model_name='player',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
