# Generated by Django 5.2.7 on 2025-10-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlayerClub_Data', '0002_rename_red_cards_player_blocks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
