# Generated by Django 5.2.6 on 2025-10-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_favorite_team_profile_instagram_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_league',
            field=models.CharField(blank=True, choices=[('EPL', 'English Premier League'), ('LALIGA', 'La Liga'), ('SERIEA', 'Serie A'), ('BUNDESLIGA', 'Bundesliga'), ('LIGUE1', 'Ligue 1'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_position',
            field=models.CharField(blank=True, choices=[('FW', 'Forward'), ('MF', 'Midfielder'), ('DF', 'Defender'), ('GK', 'Goalkeeper')], max_length=20, null=True),
        ),
    ]
