# Generated by Django 5.2.6 on 2025-10-24 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer_rumour', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferrumour',
            name='cover_image_url',
            field=models.URLField(blank=True),
        ),
    ]
