# Generated by Django 6.0 on 2025-12-11 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlayerClub_Data', '0003_player_image_url'),
        ('dream_squad', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DreamSquad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dream_squads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DreamSquadPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_dream_squads', to='PlayerClub_Data.player')),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='dream_squad.dreamsquad')),
            ],
            options={
                'ordering': ('added_at',),
                'unique_together': {('squad', 'player')},
            },
        ),
        migrations.DeleteModel(
            name='DreamSquad',
        ),
    ]
