# Generated by Django 6.0 on 2025-12-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream_squad', '0003_dreamsquad_delete_favoriteplayer'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannedWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50, unique=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
