# Generated by Django 5.2.7 on 2025-10-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='posts/'),
        ),
        migrations.AddField(
            model_name='post',
            name='media_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
