# Generated by Django 5.2.7 on 2025-12-20 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_post_attachment_post_media_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='attachment',
        ),
    ]
